[2021-11-18 10:37:47] Request: 
open_dataset(ds_id=esacci.AEROSOL.climatology.L3.AAI.multi-sensor.multi-platform.MSAAI.1-7.r1, store_id=cci-store, time_range=None, var_names=['positive_absorbing_aerosol_index', 'number_of_observations'], region=None)

Traceback (most recent call last):
  File "/home/tonio-bc/projects/ccitools/cate-e2e/testing-cci-datasets/test_cci_data_support.py", line 358, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/tonio-bc/projects/ccitools/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/tonio-bc/projects/ccitools/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/tonio-bc/projects/ccitools/cate/cate/core/ds.py", line 450, in open_dataset
    dataset = data_store.open_data(data_id=dataset_id, opener_id=opener_id, **open_args)
  File "/home/tonio-bc/projects/dcs4cop/xcube-cci/xcube_cci/dataaccess.py", line 499, in open_data
    return self._get_opener(opener_id=opener_id).open_data(data_id, **open_params)
  File "/home/tonio-bc/projects/dcs4cop/xcube-cci/xcube_cci/dataaccess.py", line 298, in open_data
    chunk_store = CciChunkStore(self._cci_odp, data_id, cube_kwargs)
  File "/home/tonio-bc/projects/dcs4cop/xcube-cci/xcube_cci/chunkstore.py", line 731, in __init__
    super().__init__(dataset_id,
  File "/home/tonio-bc/projects/dcs4cop/xcube-cci/xcube_cci/chunkstore.py", line 87, in __init__
    raise ValueError('Could not determine any valid time stamps')
ValueError: Could not determine any valid time stamps
[2021-11-18 11:05:48] Request: 
open_dataset(ds_id=esacci.AEROSOL.climatology.L3.AAI.multi-sensor.multi-platform.MSAAI.1-7.r1, store_id=cci-store, time_range=None, var_names=['absorbing_aerosol_index', 'absorbing_aerosol_index'], region=None)

Traceback (most recent call last):
  File "/home/tonio-bc/projects/ccitools/cate-e2e/testing-cci-datasets/test_cci_data_support.py", line 362, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/tonio-bc/projects/ccitools/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/tonio-bc/projects/ccitools/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/tonio-bc/projects/ccitools/cate/cate/core/ds.py", line 450, in open_dataset
    dataset = data_store.open_data(data_id=dataset_id, opener_id=opener_id, **open_args)
  File "/home/tonio-bc/projects/dcs4cop/xcube-cci/xcube_cci/dataaccess.py", line 499, in open_data
    return self._get_opener(opener_id=opener_id).open_data(data_id, **open_params)
  File "/home/tonio-bc/projects/dcs4cop/xcube-cci/xcube_cci/dataaccess.py", line 298, in open_data
    chunk_store = CciChunkStore(self._cci_odp, data_id, cube_kwargs)
  File "/home/tonio-bc/projects/dcs4cop/xcube-cci/xcube_cci/chunkstore.py", line 731, in __init__
    super().__init__(dataset_id,
  File "/home/tonio-bc/projects/dcs4cop/xcube-cci/xcube_cci/chunkstore.py", line 87, in __init__
    raise ValueError('Could not determine any valid time stamps')
ValueError: Could not determine any valid time stamps
