[2021-05-27 16:09:01] Request: 
open_dataset(ds_id=esacci.SEAICE.mon.L3C.SITHICK.SIRAL.CryoSat-2.SH50KMEASE2.2-0.r1, store_id=cci-store, time_range=None, var_names=['lon', 'sea_ice_thickness_uncertainty'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 366, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
[2021-05-27 16:38:13] Request: 
open_dataset(ds_id=esacci.SEAICE.mon.L3C.SITHICK.SIRAL.CryoSat-2.SH50KMEASE2.2-0.r1, store_id=cci-store, time_range=None, var_names=['radar_freeboard', 'sea_ice_thickness'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 369, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
[2021-05-27 17:12:00] Request: 
open_dataset(ds_id=esacci.SEAICE.mon.L3C.SITHICK.SIRAL.CryoSat-2.SH50KMEASE2.2-0.r1, store_id=cci-store, time_range=None, var_names=['status_flag', 'sea_ice_thickness'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 369, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
